version: "3"

services:
  bwrs:
    image: bitwardenrs/server
    restart: unless-stopped
    volumes:
      - ./bwdata:/data
    env_file:
      - .env
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    env_file:
      - .caddyenv
    links:
      - bwrs
